import LayoutProvider from "@/components/LayoutProvider"
import "./globals.css"
import "./../stylesheets/commonClasses.css"
import "./../stylesheets/antdOverrides.css"
import "./../stylesheets/layout.css"
import "./../stylesheets/loading.css"
import type { Metadata } from "next"
import ReduxProvider from "@/components/ReduxProvider"

export const metadata: Metadata = {
  title: "Omega Jobs",
  description: "Generated by create next app",
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <ReduxProvider>
      <LayoutProvider>{children}</LayoutProvider>
    </ReduxProvider>
  )
}
